name: form_conversation
description: A form package in conversation format.
version: 2.0.0
homepage: https://github.com/fldnascimento/form_conversation

environment:
  sdk: ^3.5.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
